name: FoL
channels:
  - xformers
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9.19
  - pytorch::pytorch==2.0.0
  - pytorch::pytorch-cuda=11.7
  - pytorch::torchvision==0.15.0
  - xformers
  - pip
  - pip:
    - faiss-gpu==1.7.2
    - pandas==1.4.1
    - prettytable==3.10.0
    - pytorch-metric-learning==2.3.0
    - torchmetrics==1.5.2